import { isSupabaseConfigured, supabase } from './supabase.js';

const PROVIDERS = new Set(['airbnb', 'booking_com', 'vrbo', 'manual', 'other']);
const STATUSES = new Set(['active', 'paused', 'error', 'disabled']);

function text(value) { const t = String(value ?? '').trim(); return t || null; }
function requireWorkspaceId(workspaceId) { const w = text(workspaceId); if (!w) return { ok:false, result:{ data:[], error:'Select an active workspace before loading calendar records.', code:'missing_workspace_id' } }; return { ok:true, workspaceId:w }; }
function notConfigured(data=[]) { return { data, error:null, code:'supabase_not_configured', notConfigured:true, message:'Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.' }; }
function safeDate(value){ if(!value) return null; const d = new Date(value); return Number.isNaN(d.getTime()) ? null : d.toISOString(); }
function safeUrl(value){ const u=text(value); if(!u) return null; try{ const parsed=new URL(u); if(!['https:','http:'].includes(parsed.protocol)) return null; if(parsed.username||parsed.password) return null; return parsed.toString(); }catch{return null;} }
function normalizeProvider(value){ const key=String(value||'').trim().toLowerCase(); if(['booking','booking.com'].includes(key)) return 'booking_com'; if(PROVIDERS.has(key)) return key; return 'other'; }
function normalizeStatus(value){ const key=String(value||'').trim().toLowerCase(); return STATUSES.has(key) ? key : 'active'; }

export function normalizeCalendarImportFeed(row){ if(!row) return null; return { ...row, propertyId: row.property_id ?? null, workspaceId: row.workspace_id ?? null, createdBy: row.created_by ?? null, provider: normalizeProvider(row.provider_type || row.provider), status: normalizeStatus(row.status), name: text(row.name) || 'Calendar feed', feedUrl: safeUrl(row.feed_url || row.ical_url || row.url) }; }
export function normalizeCalendarImportEvent(row){ if(!row) return null; return { ...row, workspaceId: row.workspace_id ?? null, propertyId: row.property_id ?? null, feedId: row.feed_id ?? null, startsAt: safeDate(row.starts_at || row.start_at), endsAt: safeDate(row.ends_at || row.end_at), status: text(row.status) || 'imported', source: normalizeProvider(row.provider || row.source_platform || 'other') }; }

export function buildCalendarImportFeedPayload(values={}){ return { name: text(values.name), property_id: text(values.property_id), feed_url: safeUrl(values.feed_url || values.ical_url || values.url), provider_type: normalizeProvider(values.provider_type || values.provider), status: normalizeStatus(values.status), import_as: text(values.import_as), notes: text(values.notes) }; }

export async function listCalendarImportFeeds({ workspaceId }={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return w.result; if(!isSupabaseConfigured||!supabase) return notConfigured([]); const {data,error}=await supabase.from('calendar_import_feeds').select('*').eq('workspace_id',w.workspaceId).order('created_at',{ascending:false}); if(error) return {data:[], error:error.message||'Calendar feeds could not be loaded.', code:error.code||'calendar_feeds_load_failed'}; return {data:(data||[]).map(normalizeCalendarImportFeed), error:null, code:'ok'}; }
export async function getCalendarImportFeedById({ workspaceId, feedId }={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const id=text(feedId); if(!id) return {data:null,error:'Select a feed first.',code:'missing_feed_id'}; if(!isSupabaseConfigured||!supabase) return notConfigured(null); const {data,error}=await supabase.from('calendar_import_feeds').select('*').eq('workspace_id',w.workspaceId).eq('id',id).single(); if(error) return {data:null,error:error.message||'Calendar feed could not be loaded.', code:error.code||'calendar_feed_load_failed'}; return {data:normalizeCalendarImportFeed(data),error:null,code:'ok'}; }
export async function createCalendarImportFeed({ workspaceId, userId, values }={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; if(!isSupabaseConfigured||!supabase) return notConfigured(null); const payload=buildCalendarImportFeedPayload(values); payload.workspace_id=w.workspaceId; payload.created_by=text(userId); const {data,error}=await supabase.from('calendar_import_feeds').insert(payload).select('*').single(); if(error) return {data:null,error:error.message||'Could not save iCal feed. Check permissions and try again.',code:error.code||'calendar_feed_insert_failed'}; return {data:normalizeCalendarImportFeed(data),error:null,code:'ok'}; }
export async function updateCalendarImportFeed({ workspaceId, feedId, values }={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const id=text(feedId); if(!id) return {data:null,error:'Select a feed first.',code:'missing_feed_id'}; if(!isSupabaseConfigured||!supabase) return notConfigured(null); const payload=buildCalendarImportFeedPayload(values); const {data,error}=await supabase.from('calendar_import_feeds').update(payload).eq('workspace_id',w.workspaceId).eq('id',id).select('*').single(); if(error) return {data:null,error:error.message||'Could not update iCal feed. Check permissions and try again.',code:error.code||'calendar_feed_update_failed'}; return {data:normalizeCalendarImportFeed(data),error:null,code:'ok'}; }
export async function listCalendarImportEvents({ workspaceId }={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return w.result; if(!isSupabaseConfigured||!supabase) return notConfigured([]); const {data,error}=await supabase.from('calendar_import_events').select('*').eq('workspace_id',w.workspaceId).order('starts_at',{ascending:true}); if(error) return {data:[],error:error.message||'Imported events could not be loaded.',code:error.code||'calendar_events_load_failed'}; return {data:(data||[]).map(normalizeCalendarImportEvent),error:null,code:'ok'}; }

export function buildWorkspaceCalendarEvents({ workspaceId, properties=[], bookings=[], cleaningTasks=[], maintenanceWorkOrders=[], importedEvents=[] }={}){
  if(!text(workspaceId)) return [];
  const map = new Map(properties.map((p)=>[p.id,p.name]));
  const propName=(id,fallback)=>map.get(id)||fallback||'Unassigned property';
  const out=[];
  bookings.forEach((b)=>{ const propertyId=b.propertyId||b.property_id||null; const ci=safeDate(b.checkIn||b.check_in); const co=safeDate(b.checkOut||b.check_out); const guest=b.guestName||b.guest_name||'Guest'; const status=text(b.status)||'confirmed'; const source=text(b.source||b.platform)||'manual'; if(ci&&co) out.push({id:`booking-${b.id}`,title:`Stay: ${guest}`,type:'booking',start:ci,end:co,propertyId,propertyName:propName(propertyId,b.property),status,source,relatedRecordId:b.id,metadata:{kind:'stay_range'}}); if(ci) out.push({id:`checkin-${b.id}`,title:`Check-in: ${guest}`,type:'checkin',start:ci,end:ci,propertyId,propertyName:propName(propertyId,b.property),status,source,relatedRecordId:b.id,metadata:{kind:'check_in'}}); if(co) out.push({id:`checkout-${b.id}`,title:`Check-out: ${guest}`,type:'checkout',start:co,end:co,propertyId,propertyName:propName(propertyId,b.property),status,source,relatedRecordId:b.id,metadata:{kind:'check_out'}}); });
  cleaningTasks.forEach((t)=>{ const when=safeDate(t.scheduledFor||t.scheduled_for); if(!when) return; const propertyId=t.propertyId||t.property_id||null; out.push({id:`cleaning-${t.id}`,title:`Cleaning: ${propName(propertyId,t.property)}`,type:'cleaning',start:when,end:when,propertyId,propertyName:propName(propertyId,t.property),status:text(t.status)||'scheduled',source:'cleaning_tasks',relatedRecordId:t.id,metadata:{}}); });
  maintenanceWorkOrders.forEach((w)=>{ const when=safeDate(w.due||w.due_date||w.date); if(!when) return; const propertyId=w.propertyId||w.property_id||null; out.push({id:`maintenance-${w.id}`,title:`Maintenance: ${w.title||'Work order'}`,type:'maintenance',start:when,end:when,propertyId,propertyName:propName(propertyId,w.property),status:text(w.status)||'reported',source:'maintenance_work_orders',relatedRecordId:w.id,metadata:{priority:text(w.priority)||'medium'}}); });
  importedEvents.forEach((e)=>{ const s=safeDate(e.startsAt||e.starts_at||e.start_at); const en=safeDate(e.endsAt||e.ends_at||e.end_at); if(!s||!en) return; const propertyId=e.propertyId||e.property_id||null; out.push({id:`imported-${e.id}`,title:text(e.title)||'Imported iCal event',type:'imported',start:s,end:en,propertyId,propertyName:propName(propertyId,e.property_name),status:text(e.status)||'imported',source:text(e.provider||e.source)||'ical',relatedRecordId:e.id,metadata:{feedId:e.feedId||e.feed_id||null}}); });
  return out;
}
