import { supabase, isSupabaseConfigured } from './supabase.js';

const CLEANING_FIELDS = ['property_id','related_booking_id','booking_id','assigned_cleaner_id','scheduled_for','status','checklist_items','cleaner_notes','supplies_used','low_supplies_reported','issue_reported','guest_ready','started_at','completed_at','before_photos','after_photos','created_by'];
const STATUS_VALUES = new Set(['scheduled','in_progress','needs_inspection','completed','guest_ready','missed','cancelled']);

const asText = (v) => { const t = String(v ?? '').trim(); return t || null; };
const asArray = (v) => Array.isArray(v) ? v : [];
function cleanArray(value){ return asArray(value).map((i)=>String(i ?? '').trim()).filter(Boolean); }
function requireWorkspaceId(workspaceId){ const w=asText(workspaceId); if(!w) return {ok:false,result:{data:[],error:'Select or create an active workspace before loading cleaning tasks.',code:'missing_workspace_id'}}; return {ok:true,workspaceId:w}; }
function notConfiguredResult(data=[]){ return {data,error:null,code:'supabase_not_configured',notConfigured:true,message:'Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to load real cleaning tasks.'}; }
function userSafeError(error,fallback){ const code=error?.code||''; const message=String(error?.message||error||'').toLowerCase(); if(code==='PGRST116') return 'Cleaning task not found.'; if(code==='42501'||message.includes('row-level security')||message.includes('permission denied')) return 'You do not have permission to save this cleaning task in the active workspace.'; if(message.includes('violates check constraint')) return 'Cleaning task contains an unsupported value.'; if(message.includes('violates not-null constraint')||message.includes('null value')) return 'Cleaning task is missing required fields.'; if(message.includes('failed to fetch')||message.includes('network')) return 'Network issue while saving cleaning task. Check your connection and try again.'; return fallback; }

export function normalizeCleaningTask(row=null){ if(!row) return null; const relatedBookingId=row.related_booking_id ?? row.booking_id ?? row.relatedBookingId ?? row.bookingId ?? null; return {...row, propertyId:row.property_id ?? null, related_booking_id: relatedBookingId, relatedBookingId, booking_id:relatedBookingId, bookingId:relatedBookingId, assignedCleanerId:row.assigned_cleaner_id ?? null, scheduledFor:row.scheduled_for ?? '', checklist_items:cleanArray(row.checklist_items), checklist:cleanArray(row.checklist_items), cleanerNotes:row.cleaner_notes || '', suppliesUsed:row.supplies_used || '', lowSuppliesReported:Boolean(row.low_supplies_reported), issueReported:Boolean(row.issue_reported), guestReady:Boolean(row.guest_ready ?? row.status === 'guest_ready'), beforePhotos:cleanArray(row.before_photos), afterPhotos:cleanArray(row.after_photos), startedAt:row.started_at ?? null, completedAt:row.completed_at ?? null}; }

export function buildCleaningTaskPayload(values={}){ const payload={}; for(const k of CLEANING_FIELDS){ if(Object.prototype.hasOwnProperty.call(values,k)) payload[k]=values[k]; }
 if('booking_id' in payload && !('related_booking_id' in payload)) payload.related_booking_id=payload.booking_id;
 if('related_booking_id' in payload && !('booking_id' in payload)) payload.booking_id=payload.related_booking_id;
 ['property_id','related_booking_id','assigned_cleaner_id','created_by'].forEach((k)=>{ if(k in payload) payload[k]=asText(payload[k]); });
 ['cleaner_notes','supplies_used','scheduled_for','started_at','completed_at'].forEach((k)=>{ if(k in payload) payload[k]=asText(payload[k]); });
 if('status' in payload){ const s=String(payload.status||'').trim().toLowerCase(); payload.status=s||'scheduled'; if(!STATUS_VALUES.has(payload.status)) throw new Error('Select a valid cleaning status.'); }
 if('checklist_items' in payload) payload.checklist_items=cleanArray(payload.checklist_items);
 if('before_photos' in payload) payload.before_photos=cleanArray(payload.before_photos);
 if('after_photos' in payload) payload.after_photos=cleanArray(payload.after_photos);
 ['low_supplies_reported','issue_reported','guest_ready'].forEach((k)=>{ if(k in payload) payload[k]=Boolean(payload[k]); });
 return payload; }

export async function listCleaningTasks({workspaceId}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return w.result; if(!isSupabaseConfigured||!supabase) return notConfiguredResult([]); const {data,error}=await supabase.from('cleaning_tasks').select('*').eq('workspace_id',w.workspaceId).order('scheduled_for',{ascending:true}); if(error) return {data:[],error:userSafeError(error,'Cleaning tasks could not be loaded.'),code:error.code||'cleaning_tasks_load_failed'}; return {data:(data||[]).map(normalizeCleaningTask),error:null,code:'ok'}; }
export async function getCleaningTaskById({workspaceId,taskId}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const t=asText(taskId); if(!t) return {data:null,error:'Select a cleaning task before loading details.',code:'missing_cleaning_task_id'}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); const {data,error}=await supabase.from('cleaning_tasks').select('*').eq('workspace_id',w.workspaceId).eq('id',t).single(); if(error) return {data:null,error:userSafeError(error,'Cleaning task not found.'),code:error.code||'cleaning_task_load_failed'}; return {data:normalizeCleaningTask(data),error:null,code:'ok'}; }
export async function createCleaningTask({workspaceId,userId,values}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); let payload; try{ payload=buildCleaningTaskPayload(values);}catch(e){ return {data:null,error:e.message,code:'invalid_cleaning_task_payload'}; } payload.workspace_id=w.workspaceId; payload.created_by=asText(userId)||payload.created_by||null; const {data,error}=await supabase.from('cleaning_tasks').insert(payload).select('*').single(); if(error) return {data:null,error:userSafeError(error,'Cleaning task could not be saved.'),code:error.code||'cleaning_task_insert_failed'}; return {data:normalizeCleaningTask(data),error:null,code:'ok'}; }
export async function updateCleaningTask({workspaceId,taskId,values}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const t=asText(taskId); if(!t) return {data:null,error:'Select a cleaning task before saving changes.',code:'missing_cleaning_task_id'}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); let payload; try{ payload=buildCleaningTaskPayload(values);}catch(e){ return {data:null,error:e.message,code:'invalid_cleaning_task_payload'}; } const {data,error}=await supabase.from('cleaning_tasks').update(payload).eq('id',t).eq('workspace_id',w.workspaceId).select('*').single(); if(error) return {data:null,error:userSafeError(error,'Cleaning task could not be updated.'),code:error.code||'cleaning_task_update_failed'}; return {data:normalizeCleaningTask(data),error:null,code:'ok'}; }
