import { supabase, isSupabaseConfigured } from './supabase.js';

const MAINTENANCE_FIELDS = [
  'property_id','assigned_maintenance_id','assigned_company_id','reported_by_user_id','reported_by_source','title','description','issue_description','priority','status','estimated_cost','actual_cost','parts_needed','materials_needed','due_date','notes','issue_photos','issue_videos','completion_photos','completion_videos','updates','history','completed_at','created_by',
];
const PRIORITY_VALUES = new Set(['low','medium','high','urgent']);
const STATUS_VALUES = new Set(['reported','assigned','in_progress','waiting_parts','completed','cancelled']);

const asText = (v) => { const t = String(v ?? '').trim(); return t || null; };
const asArray = (v) => Array.isArray(v) ? v : [];
const cleanArray = (v) => asArray(v).map((i)=>String(i ?? '').trim()).filter(Boolean);
function cleanNumber(v){ if(v===''||v===null||v===undefined) return null; const c=String(v).replace(/,/g,'').replace(/[^\d.-]/g,'').trim(); if(!c||c==='-'||c==='.'||c==='-.') return null; const n=Number(c); if(!Number.isFinite(n)) return null; if(n<0) throw new Error('Cost values must be 0 or more.'); return n; }
function requireWorkspaceId(workspaceId){ const w=asText(workspaceId); if(!w) return {ok:false,result:{data:[],error:'Select or create an active workspace before loading maintenance work orders.',code:'missing_workspace_id'}}; return {ok:true,workspaceId:w}; }
function notConfiguredResult(data=[]){ return {data,error:null,code:'supabase_not_configured',notConfigured:true,message:'Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to load real maintenance work orders.'}; }
function userSafeError(error,fallback){ const code=error?.code||''; const message=String(error?.message||error||'').toLowerCase(); if(code==='PGRST116') return 'Maintenance work order not found.'; if(code==='42501'||message.includes('row-level security')||message.includes('permission denied')) return 'You do not have permission to save this maintenance work order in the active workspace.'; if(message.includes('violates check constraint')) return 'Maintenance work order contains an unsupported value.'; if(message.includes('violates not-null constraint')||message.includes('null value')) return 'Maintenance work order is missing required fields.'; if(message.includes('failed to fetch')||message.includes('network')) return 'Network issue while saving maintenance work order. Check your connection and try again.'; return fallback; }

export function normalizeMaintenanceWorkOrder(row=null){ if(!row) return null; return {...row, propertyId:row.property_id ?? null, assignedMaintenanceId:row.assigned_maintenance_id ?? null, assignedCompanyId:row.assigned_company_id ?? null, reportedBySource:row.reported_by_source || 'manual', issueDescription:row.description || row.issue_description || '', description:row.description || row.issue_description || '', estimatedCost:row.estimated_cost ?? null, actualCost:row.actual_cost ?? null, partsNeeded:row.parts_needed || '', materialsNeeded:row.materials_needed || '', due:row.due_date || '', issuePhotos:cleanArray(row.issue_photos), issueVideos:cleanArray(row.issue_videos), completionPhotos:cleanArray(row.completion_photos), completionVideos:cleanArray(row.completion_videos), updates:asArray(row.updates), history:asArray(row.history)}; }

export function buildMaintenanceWorkOrderPayload(values={}){ const payload={}; for(const k of MAINTENANCE_FIELDS){ if(Object.prototype.hasOwnProperty.call(values,k)) payload[k]=values[k]; }
 if('issue_description' in payload && !('description' in payload)) payload.description=payload.issue_description;
 ['property_id','assigned_maintenance_id','assigned_company_id','reported_by_user_id','created_by'].forEach((k)=>{ if(k in payload) payload[k]=asText(payload[k]); });
 ['title','description','reported_by_source','parts_needed','materials_needed','notes','due_date','completed_at'].forEach((k)=>{ if(k in payload) payload[k]=asText(payload[k]); });
 if('priority' in payload){ const p=String(payload.priority||'').trim().toLowerCase(); payload.priority=p||'medium'; if(!PRIORITY_VALUES.has(payload.priority)) throw new Error('Select a valid maintenance priority.'); }
 if('status' in payload){ const s=String(payload.status||'').trim().toLowerCase(); payload.status=s||'reported'; if(!STATUS_VALUES.has(payload.status)) throw new Error('Select a valid maintenance status.'); }
 if('estimated_cost' in payload) payload.estimated_cost=cleanNumber(payload.estimated_cost);
 if('actual_cost' in payload) payload.actual_cost=cleanNumber(payload.actual_cost);
 ['issue_photos','issue_videos','completion_photos','completion_videos'].forEach((k)=>{ if(k in payload) payload[k]=cleanArray(payload[k]); });
 ['updates','history'].forEach((k)=>{ if(k in payload) payload[k]=asArray(payload[k]); });
 if('issue_description' in payload) delete payload.issue_description;
 return payload; }

export async function listMaintenanceWorkOrders({workspaceId}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return w.result; if(!isSupabaseConfigured||!supabase) return notConfiguredResult([]); const {data,error}=await supabase.from('maintenance_work_orders').select('*').eq('workspace_id',w.workspaceId).order('created_at',{ascending:false}); if(error) return {data:[],error:userSafeError(error,'Maintenance work orders could not be loaded.'),code:error.code||'maintenance_work_orders_load_failed'}; return {data:(data||[]).map(normalizeMaintenanceWorkOrder),error:null,code:'ok'}; }
export async function getMaintenanceWorkOrderById({workspaceId,workOrderId}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const id=asText(workOrderId); if(!id) return {data:null,error:'Select a maintenance work order before loading details.',code:'missing_work_order_id'}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); const {data,error}=await supabase.from('maintenance_work_orders').select('*').eq('workspace_id',w.workspaceId).eq('id',id).single(); if(error) return {data:null,error:userSafeError(error,'Maintenance work order not found.'),code:error.code||'maintenance_work_order_load_failed'}; return {data:normalizeMaintenanceWorkOrder(data),error:null,code:'ok'}; }
export async function createMaintenanceWorkOrder({workspaceId,userId,values}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); let payload; try{ payload=buildMaintenanceWorkOrderPayload(values);}catch(e){ return {data:null,error:e.message,code:'invalid_maintenance_work_order_payload'}; } payload.workspace_id=w.workspaceId; payload.created_by=asText(userId)||payload.created_by||null; const {data,error}=await supabase.from('maintenance_work_orders').insert(payload).select('*').single(); if(error) return {data:null,error:userSafeError(error,'Maintenance work order could not be saved.'),code:error.code||'maintenance_work_order_insert_failed'}; return {data:normalizeMaintenanceWorkOrder(data),error:null,code:'ok'}; }
export async function updateMaintenanceWorkOrder({workspaceId,workOrderId,values}={}){ const w=requireWorkspaceId(workspaceId); if(!w.ok) return {...w.result,data:null}; const id=asText(workOrderId); if(!id) return {data:null,error:'Select a maintenance work order before saving changes.',code:'missing_work_order_id'}; if(!isSupabaseConfigured||!supabase) return notConfiguredResult(null); let payload; try{ payload=buildMaintenanceWorkOrderPayload(values);}catch(e){ return {data:null,error:e.message,code:'invalid_maintenance_work_order_payload'}; } const {data,error}=await supabase.from('maintenance_work_orders').update(payload).eq('id',id).eq('workspace_id',w.workspaceId).select('*').single(); if(error) return {data:null,error:userSafeError(error,'Maintenance work order could not be updated.'),code:error.code||'maintenance_work_order_update_failed'}; return {data:normalizeMaintenanceWorkOrder(data),error:null,code:'ok'}; }
