import React from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Eye } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { EmptyState } from '../components/EmptyState.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { currencies } from '../data/constants.js';

const bookingStatuses = ['pending','confirmed','checked_in','checked_out','completed','cancelled'];
const cleaningStatuses = ['scheduled','in_progress','completed','missed','needs_inspection','guest_ready','cancelled'];
const priorities = ['low','medium','high','urgent'];
const sources = ['manual','direct','airbnb','booking_com','vrbo','ical','csv','other'];
const views = ['month','week','day','agenda'];
const dateOnly = (date) => new Date(date).toISOString().slice(0, 10);
const addDays = (date, days) => { const next = new Date(date); next.setDate(next.getDate() + days); return next; };
const startOfWeek = (date) => addDays(date, -date.getDay());
const startOfMonthGrid = (date) => startOfWeek(new Date(date.getFullYear(), date.getMonth(), 1));
const sameDay = (a, b) => dateOnly(a) === dateOnly(b);
const overlapsDay = (event, day) => event.start <= dateOnly(day) && event.end >= dateOnly(day);
function buildDays(anchor, view) { if (view === 'day') return [new Date(anchor)]; if (view === 'week') return Array.from({ length: 7 }, (_, i) => addDays(startOfWeek(anchor), i)); return Array.from({ length: 42 }, (_, i) => addDays(startOfMonthGrid(anchor), i)); }
function eventTone(type) { return { booking:'event-booking', checkin:'event-info', checkout:'event-warning', cleaning:'event-cleaning', maintenance:'event-error', lease:'event-lease' }[type] || 'event-info'; }

function makeEvents(data) {
  const bookingEvents = data.bookings.flatMap((booking) => [
    { id:`booking-${booking.id}`, sourceId:booking.id, type:'booking', title:booking.guest_name, propertyId:booking.property_id, property:booking.property, start:booking.check_in, end:booking.check_out, status:booking.status, source:booking.source, ownerId:null, assignedId:null, priority:null, row:booking },
    { id:`checkin-${booking.id}`, sourceId:booking.id, type:'checkin', title:`Check-in: ${booking.guest_name}`, propertyId:booking.property_id, property:booking.property, start:booking.check_in, end:booking.check_in, status:booking.status, source:booking.source, row:booking },
    { id:`checkout-${booking.id}`, sourceId:booking.id, type:'checkout', title:`Check-out: ${booking.guest_name}`, propertyId:booking.property_id, property:booking.property, start:booking.check_out, end:booking.check_out, status:booking.status, source:booking.source, row:booking },
  ]);
  const leaseEvents = data.leases.flatMap((lease) => [
    { id:`lease-${lease.id}`, sourceId:lease.id, type:'lease', title:`Lease: ${lease.tenant_name}`, propertyId:lease.property_id, property:lease.property, start:lease.lease_start, end:lease.lease_end || dateOnly(addDays(new Date(), 365)), status:lease.lease_status, row:lease },
    { id:`lease-start-${lease.id}`, sourceId:lease.id, type:'lease', title:`Lease starts: ${lease.tenant_name}`, propertyId:lease.property_id, property:lease.property, start:lease.lease_start, end:lease.lease_start, status:lease.lease_status, row:lease },
    ...(lease.lease_end ? [{ id:`lease-end-${lease.id}`, sourceId:lease.id, type:'lease', title:`Lease ends: ${lease.tenant_name}`, propertyId:lease.property_id, property:lease.property, start:lease.lease_end, end:lease.lease_end, status:lease.lease_status, row:lease }] : []),
  ]);
  const cleaningEvents = data.cleaningTasks.map((task) => ({ id:`cleaning-${task.id}`, sourceId:task.id, type:'cleaning', title:`Cleaning: ${task.property}`, propertyId:task.propertyId, property:task.property, start:dateOnly(task.scheduledFor), end:dateOnly(task.scheduledFor), status:task.status, assignedId:task.assignedCleanerId, row:task }));
  const maintenanceEvents = data.maintenanceWorkOrders.filter((work) => work.due).map((work) => ({ id:`maintenance-${work.id}`, sourceId:work.id, type:'maintenance', title:`Maintenance: ${work.title}`, propertyId:work.propertyId, property:work.property, start:work.due, end:work.due, status:work.status, priority:work.priority, assignedId:work.assignedMaintenanceId, row:work }));
  return [...bookingEvents, ...leaseEvents, ...cleaningEvents, ...maintenanceEvents];
}

export function CalendarPage() {
  const { data } = useApp();
  const [view, setView] = React.useState('month');
  const [anchor, setAnchor] = React.useState(new Date());
  const [selected, setSelected] = React.useState(null);
  const [filters, setFilters] = React.useState({ property:'all', start:'', end:'', bookingStatus:'all', cleaningStatus:'all', priority:'all', assigned:'all', owner:'all', source:'all', currency:'all', showCancelled:false });
  const setFilter = (key) => (event) => setFilters((value) => ({ ...value, [key]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }));
  const events = React.useMemo(() => makeEvents(data).filter((event) => filters.showCancelled || !['cancelled','terminated'].includes(event.status)).filter((event) => filters.property === 'all' || event.propertyId === filters.property).filter((event) => !filters.start || event.end >= filters.start).filter((event) => !filters.end || event.start <= filters.end).filter((event) => filters.bookingStatus === 'all' || !['booking','checkin','checkout'].includes(event.type) || event.status === filters.bookingStatus).filter((event) => filters.cleaningStatus === 'all' || event.type !== 'cleaning' || event.status === filters.cleaningStatus).filter((event) => filters.priority === 'all' || event.type !== 'maintenance' || event.priority === filters.priority).filter((event) => filters.assigned === 'all' || event.assignedId === filters.assigned).filter((event) => filters.owner === 'all' || data.properties.find((property) => property.id === event.propertyId)?.assignedOwnerId === filters.owner).filter((event) => filters.source === 'all' || !['booking','checkin','checkout'].includes(event.type) || event.source === filters.source).filter((event) => filters.currency === 'all' || !event.row?.currency || event.row.currency === filters.currency), [data, filters]);
  const visibleDays = buildDays(anchor, view);
  const members = data.members.map((member) => ({ id:member.user_id, label:member.profile?.full_name || member.profile?.email || member.profiles?.full_name || member.profiles?.email || member.user_id }));
  const move = (direction) => { const days = view === 'day' ? 1 : view === 'week' ? 7 : 30; setAnchor((date) => addDays(date, direction * days)); };

  const agenda = events.slice().sort((a, b) => a.start.localeCompare(b.start));
  return <AppLayout title="Calendar"><section className="card"><div className="card-header"><div><h3>Operations calendar</h3><p>Stay blocks, check-in/check-out events, cleaning tasks, maintenance due dates, and lease periods from Supabase data.</p></div><div className="action-row"><button onClick={() => move(-1)}><ChevronLeft size={16}/> Previous</button><button onClick={() => setAnchor(new Date())}>Today</button><button onClick={() => move(1)}>Next <ChevronRight size={16}/></button></div></div><div className="tabs">{views.map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item}</button>)}</div></section>
    <section className="card"><div className="filter-bar booking-filter"><select value={filters.property} onChange={setFilter('property')}><option value="all">All properties</option>{data.properties.map((property) => <option key={property.id} value={property.id}>{property.name}</option>)}</select><input type="date" value={filters.start} onChange={setFilter('start')} /><input type="date" value={filters.end} onChange={setFilter('end')} /><select value={filters.bookingStatus} onChange={setFilter('bookingStatus')}><option value="all">All booking statuses</option>{bookingStatuses.map((status) => <option key={status}>{status}</option>)}</select><select value={filters.cleaningStatus} onChange={setFilter('cleaningStatus')}><option value="all">All cleaning statuses</option>{cleaningStatuses.map((status) => <option key={status}>{status}</option>)}</select><select value={filters.priority} onChange={setFilter('priority')}><option value="all">All priorities</option>{priorities.map((priority) => <option key={priority}>{priority}</option>)}</select><select value={filters.assigned} onChange={setFilter('assigned')}><option value="all">All assigned users</option>{members.map((member) => <option key={member.id} value={member.id}>{member.label}</option>)}</select><select value={filters.owner} onChange={setFilter('owner')}><option value="all">All owners</option>{members.map((member) => <option key={member.id} value={member.id}>{member.label}</option>)}</select><select value={filters.source} onChange={setFilter('source')}><option value="all">All booking sources</option>{sources.map((source) => <option key={source}>{source}</option>)}</select><select value={filters.currency} onChange={setFilter('currency')}><option value="all">All currencies</option>{currencies.map((currency) => <option key={currency}>{currency}</option>)}</select><label className="inline-check"><input type="checkbox" checked={filters.showCancelled} onChange={setFilter('showCancelled')} /> Show cancelled</label></div></section>
    {view === 'agenda' ? <section className="card calendar-agenda">{agenda.length ? agenda.map((event) => <button className={`calendar-event ${eventTone(event.type)}`} key={event.id} onClick={() => setSelected(event)}><span>{event.start}</span><strong>{event.title}</strong><small>{event.property} · {event.type}</small><StatusBadge>{event.status}</StatusBadge></button>) : <EmptyState title="No calendar events." description="Add bookings, leases, cleaning tasks, or maintenance due dates to populate the agenda." />}</section> : <section className={`card calendar-grid calendar-${view}`}><div className="calendar-header"><CalendarDays size={18}/><strong>{anchor.toLocaleDateString(undefined, { month:'long', year:'numeric' })}</strong><span className="property-timeline-note">Property timeline view is prepared for a future phase.</span></div><div className="calendar-days">{visibleDays.map((day) => { const dayEvents = events.filter((event) => overlapsDay(event, day)).slice(0, view === 'month' ? 4 : 12); return <div className={`calendar-day ${sameDay(day, new Date()) ? 'today' : ''}`} key={day.toISOString()}><strong>{day.toLocaleDateString(undefined, { weekday:view === 'month' ? 'short' : 'long', month:'short', day:'numeric' })}</strong>{dayEvents.map((event) => <button key={`${day.toISOString()}-${event.id}`} className={`calendar-event ${eventTone(event.type)}`} onClick={() => setSelected(event)}><span>{event.type}</span>{event.title}</button>)}{events.filter((event) => overlapsDay(event, day)).length > dayEvents.length && <small>+ more</small>}</div>; })}</div></section>}
    {selected && <section className="card detail-panel"><div className="card-header"><div><h3>{selected.title}</h3><p>{selected.property} · {selected.start} {selected.end !== selected.start ? `→ ${selected.end}` : ''}</p></div><button onClick={() => setSelected(null)}>Close</button></div><div className="metadata-grid"><span><Eye size={16}/> Type: {selected.type}</span><span>Status: <StatusBadge>{selected.status}</StatusBadge></span><span>Source: {selected.source || 'internal'}</span><span>Future: drag/drop hooks pending</span></div><pre>{JSON.stringify(selected.row, null, 2)}</pre></section>}
  </AppLayout>;
}
