import React from 'react';
import { Activity, CalendarCheck, DollarSign, Percent, TrendingUp, Wrench } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { StatCard } from '../components/StatCard.jsx';
import { FilterBar } from '../components/FilterBar.jsx';
import { DataTable } from '../components/DataTable.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { RevenueCharts, OperationsCharts } from '../components/dashboard/DashboardCharts.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { formatCurrency, formatPercent } from '../lib/formatters.js';
import { propertyOwners } from '../data/sampleData.js';
export function DashboardPage() { const { currentWorkspace, data } = useApp(); const revenue = data.properties.reduce((s, p) => s + p.revenue, 0); const expenses = data.properties.reduce((s, p) => s + p.expenses, 0); const avgOcc = data.properties.reduce((s, p) => s + p.occupancy, 0) / (data.properties.length || 1); return <AppLayout title="Dashboard"><FilterBar properties={data.properties} owners={propertyOwners}/><div className="stat-grid"><StatCard label="Gross revenue" value={formatCurrency(revenue, currentWorkspace.defaultCurrency)} icon={DollarSign} trend="+12.4% vs last month"/><StatCard label="Net profit" value={formatCurrency(revenue - expenses, currentWorkspace.defaultCurrency)} icon={TrendingUp} trend="Healthy margin"/><StatCard label="Occupancy rate" value={formatPercent(avgOcc)} icon={Percent} trend="+6%"/><StatCard label="Operations health" value="91/100" icon={Activity} trend="2 alerts" tone="warning"/></div><RevenueCharts/><div className="panel-grid"><section className="card"><h3>Upcoming bookings</h3><DataTable rows={data.bookings} columns={[{key:'guest',label:'Guest'},{key:'property',label:'Property'},{key:'checkIn',label:'Check-in'},{key:'status',label:'Status',render:r=><StatusBadge>{r.status}</StatusBadge>}]} /></section><section className="card"><h3>Cleaning status</h3>{data.cleaningTasks.map((task)=><div className="list-row" key={task.id}><CalendarCheck size={18}/><span>{task.property}<small>{task.due}</small></span><StatusBadge>{task.status}</StatusBadge></div>)}</section><section className="card"><h3>Maintenance alerts</h3>{data.maintenanceWorkOrders.map((wo)=><div className="list-row" key={wo.id}><Wrench size={18}/><span>{wo.title}<small>{wo.property}</small></span><StatusBadge>{wo.priority}</StatusBadge></div>)}</section></div><section className="card"><div className="card-header"><div><h3>Direct booking snapshot & property performance</h3><p>Direct bookings: {data.bookings.filter(b=>b.source==='Direct').length}; workspace currency: {currentWorkspace.defaultCurrency}</p></div></div><DataTable rows={data.properties} columns={[{key:'name',label:'Property'},{key:'city',label:'City'},{key:'rentalType',label:'Rental type'},{key:'revenue',label:'Revenue',render:r=>formatCurrency(r.revenue,r.currency)},{key:'expenses',label:'Expenses',render:r=>formatCurrency(r.expenses,r.currency)},{key:'occupancy',label:'Occupancy',render:r=>formatPercent(r.occupancy)},{key:'status',label:'Status',render:r=><StatusBadge>{r.status}</StatusBadge>}]} /></section><OperationsCharts/></AppLayout>; }
