import React from 'react';
import { Building2, CalendarCheck, ClipboardList, Wrench } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { StatCard } from '../components/StatCard.jsx';
import { DataTable } from '../components/DataTable.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { EmptyState } from '../components/EmptyState.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { navigate } from '../routes/AppRouter.jsx';
export function DashboardPage() { const { data, currentWorkspace } = useApp(); const active=data.properties.filter(p=>p.status!=='archived'); const urgent=data.maintenanceWorkOrders.filter(w=>w.priority==='urgent'&&!['completed','cancelled'].includes(w.status)); return <AppLayout title="Dashboard"><section className="card"><h3>Setup progress</h3><p>Welcome to {currentWorkspace?.name}. Add properties, invite your team, then connect bookings, cleaning, maintenance, and performance workflows.</p><div className="action-row"><button className="primary" onClick={()=>navigate('/properties')}>Add property</button><button onClick={()=>navigate('/settings')}>Invite team</button></div></section><div className="stat-grid"><StatCard label="Active properties" value={active.length} icon={Building2}/><StatCard label="Cleaning tasks" value={data.cleaningTasks.length} icon={CalendarCheck}/><StatCard label="Open maintenance" value={data.maintenanceWorkOrders.filter(w=>!['completed','cancelled'].includes(w.status)).length} icon={Wrench}/><StatCard label="Urgent alerts" value={urgent.length} icon={ClipboardList} tone={urgent.length?'warning':'default'}/></div><div className="panel-grid two"><section className="card"><h3>Properties</h3>{active.length?<DataTable rows={active.slice(0,5)} columns={[{key:'name',label:'Property'},{key:'status',label:'Status',render:r=><StatusBadge>{r.status}</StatusBadge>},{key:'rental_type',label:'Rental'}]} />:<EmptyState title="No properties added yet." description="Add your first property to start managing operations." />}</section><section className="card"><h3>Maintenance alerts</h3>{urgent.length?urgent.map(wo=><div className="list-row" key={wo.id}><Wrench size={18}/><span>{wo.title}<small>{wo.property}</small></span><StatusBadge>{wo.priority}</StatusBadge></div>):<p>No urgent maintenance alerts.</p>}</section></div></AppLayout>; }
