import React from 'react';
import { currencies } from '../data/constants.js';
import { useApp } from '../lib/AppContext.jsx';
import { navigate } from '../routes/AppRouter.jsx';

const businessTypes = ['Short-term rental operator','Long-term landlord','Property management company','Cleaning company','Maintenance company','Villa / guesthouse / resort','Real estate company'];
export function JoinWorkspacePage() {
  const { createWorkspace, acceptInvite, isSupabaseConfigured, currentUser } = useApp();
  const params = new URLSearchParams(window.location.search);
  const [createForm, setCreateForm] = React.useState({ name: '', business_type: businessTypes[0], country: 'United States', default_currency: 'USD', business_email: currentUser?.email || '', phone: '', website: '', property_count_estimate: '', plan_placeholder: 'Starter' });
  const [code, setCode] = React.useState(params.get('invite') || params.get('code') || '');
  const [message, setMessage] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const set = (key) => (e) => setCreateForm((form) => ({ ...form, [key]: e.target.value }));
  const submitCreate = async (event) => { event.preventDefault(); if (!isSupabaseConfigured) { setMessage('Supabase is not configured. Workspace records require a connected Supabase project.'); return; } setBusy(true); try { await createWorkspace(createForm); navigate('/dashboard'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const submitJoin = async (event) => { event.preventDefault(); if (!isSupabaseConfigured) { setMessage('Supabase is not configured. Invite validation requires Supabase.'); return; } setBusy(true); try { await acceptInvite(code.trim()); navigate('/login/redirect'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="auth-page"><div className="auth-card wide"><h1>Create or join a workspace</h1><p>New accounts can create a workspace immediately. Company codes only work when a valid pending invite exists for your authenticated email.</p>{message && <div className="helper">{message}</div>}<div className="panel-grid two"><form className="card compact" onSubmit={submitCreate}><h3>Create workspace</h3><div className="form-grid"><label>Workspace/business name<input value={createForm.name} onChange={set('name')} required /></label><label>Business type<select value={createForm.business_type} onChange={set('business_type')}>{businessTypes.map((item)=><option key={item}>{item}</option>)}</select></label><label>Country<input value={createForm.country} onChange={set('country')} required /></label><label>Default currency<select value={createForm.default_currency} onChange={set('default_currency')}>{currencies.map((currency)=><option key={currency}>{currency}</option>)}</select></label><label>Business email<input value={createForm.business_email} onChange={set('business_email')} type="email" required /></label><label>Phone number<input value={createForm.phone} onChange={set('phone')} required /></label><label>Website optional<input value={createForm.website} onChange={set('website')} /></label><label>Number of properties managed<input value={createForm.property_count_estimate} onChange={set('property_count_estimate')} type="number" min="0" /></label><label>Subscription plan placeholder<select value={createForm.plan_placeholder} onChange={set('plan_placeholder')}><option>Starter</option><option>Growth</option><option>Scale</option></select></label></div><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Create workspace'}</button></form><form className="card compact" onSubmit={submitJoin}><h3>Join workspace</h3><p>Paste an invite token/link or workspace/company code. The database checks invite status, expiration, and email match before adding membership.</p><label>Invite link or company code<input value={code} onChange={(e)=>setCode(e.target.value.split('invite=').pop())} placeholder="BLUE-2026 or invite token" required /></label><button className="primary" disabled={busy}>Join workspace</button></form></div></div></div>;
}
