import React from 'react';
import { Plus } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { DataTable } from '../components/DataTable.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { EmptyState } from '../components/EmptyState.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { formatCurrency } from '../lib/formatters.js';
import { navigate } from '../routes/AppRouter.jsx';
import { currencies, propertyEditorRoles, propertyStatuses, propertyTypes, rentalTypes } from '../data/constants.js';
import { hasAnyRole } from '../lib/auth.js';

const initial = { name:'', address:'', city:'', state:'', country:'United States', property_type:'short_term_rental', rental_type:'short_term', currency:'USD', nightly_rate:'', monthly_rent:'', status:'active', bedrooms:'', bathrooms:'', square_feet:'', notes:'' };
function PropertyForm({ onSubmit, onCancel }) { const [form,setForm]=React.useState(initial); const set=(k)=>(e)=>setForm(v=>({...v,[k]:e.target.value})); return <form className="card" onSubmit={(e)=>{e.preventDefault(); onSubmit(form);}}><h3>Add property</h3><div className="form-grid"><label>Property name<input value={form.name} onChange={set('name')} required /></label><label>Address/location<input value={form.address} onChange={set('address')} required /></label><label>Country<input value={form.country} onChange={set('country')} required /></label><label>Property type<select value={form.property_type} onChange={set('property_type')}>{propertyTypes.map(i=><option key={i} value={i}>{i.replaceAll('_',' ')}</option>)}</select></label><label>Rental type<select value={form.rental_type} onChange={set('rental_type')}>{rentalTypes.map(i=><option key={i} value={i}>{i.replaceAll('_',' ')}</option>)}</select></label><label>Currency<select value={form.currency} onChange={set('currency')}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label>{form.rental_type !== 'long_term' && <label>Nightly rate<input value={form.nightly_rate} onChange={set('nightly_rate')} type="number" min="0" required={form.rental_type !== 'long_term'} /></label>}{form.rental_type !== 'short_term' && <label>Monthly rent<input value={form.monthly_rent} onChange={set('monthly_rent')} type="number" min="0" required={form.rental_type !== 'short_term'} /></label>}<label>Status<select value={form.status} onChange={set('status')}>{propertyStatuses.filter(s=>s!=='archived').map(i=><option key={i}>{i}</option>)}</select></label><label>City<input value={form.city} onChange={set('city')} /></label><label>State / parish<input value={form.state} onChange={set('state')} /></label><label>Bedrooms<input value={form.bedrooms} onChange={set('bedrooms')} type="number" min="0" /></label><label>Bathrooms<input value={form.bathrooms} onChange={set('bathrooms')} type="number" min="0" step="0.5" /></label><label>Square footage<input value={form.square_feet} onChange={set('square_feet')} type="number" min="0" /></label><label className="full">Notes<textarea value={form.notes} onChange={set('notes')} /></label></div><div className="action-row"><button className="primary">Save property</button><button type="button" onClick={onCancel}>Cancel</button></div></form> }
export function PropertiesPage(){ const { data, createProperty, currentUser } = useApp(); const [showForm,setShowForm]=React.useState(false); const [showArchived,setShowArchived]=React.useState(false); const [status,setStatus]=React.useState('all'); const [query,setQuery]=React.useState(''); const canEdit=hasAnyRole(currentUser, propertyEditorRoles); const rows=data.properties.filter(p=>(showArchived?true:p.status!=='archived')).filter(p=>status==='all'||p.status===status).filter(p=>`${p.name} ${p.address} ${p.city}`.toLowerCase().includes(query.toLowerCase())); const submit=async(form)=>{ await createProperty({ ...form, nightly_rate: form.nightly_rate || null, monthly_rent: form.monthly_rent || null, bedrooms: form.bedrooms || null, bathrooms: form.bathrooms || null, square_feet: form.square_feet || null }); setShowForm(false); }; return <AppLayout title="Properties"><section className="card"><div className="card-header"><div><h3>Workspace properties</h3><p>Active lists hide archived properties by default. All rows are read from Supabase.</p></div>{canEdit && <button className="primary" onClick={()=>setShowForm(true)}><Plus size={16}/> Add property</button>}</div><div className="filter-bar"><input placeholder="Search properties" value={query} onChange={e=>setQuery(e.target.value)} /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{propertyStatuses.map(s=><option key={s}>{s}</option>)}</select><label className="inline-check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)} /> Show archived</label></div></section>{showForm && <PropertyForm onSubmit={submit} onCancel={()=>setShowForm(false)} />}{rows.length ? <section className="card"><DataTable rows={rows} columns={[{key:'name',label:'Property',render:r=><button className="link" onClick={()=>navigate(`/properties/${r.id}`)}>{r.name}</button>},{key:'address',label:'Address'},{key:'city',label:'City'},{key:'country',label:'Country'},{key:'property_type',label:'Type',render:r=>r.property_type?.replaceAll('_',' ')},{key:'rental_type',label:'Rental',render:r=>r.rental_type?.replaceAll('_',' ')},{key:'bedrooms',label:'Beds'},{key:'bathrooms',label:'Baths'},{key:'nightly_rate',label:'Nightly',render:r=>r.nightly_rate?formatCurrency(r.nightly_rate,r.currency):'—'},{key:'monthly_rent',label:'Monthly',render:r=>r.monthly_rent?formatCurrency(r.monthly_rent,r.currency):'—'},{key:'status',label:'Status',render:r=><StatusBadge>{r.status}</StatusBadge>}]} /></section> : <EmptyState title="No properties added yet." description="Add your first property to start managing bookings, cleaning, maintenance, and performance." action={canEdit ? <button className="primary" onClick={()=>setShowForm(true)}>Add your first property</button> : null} />}</AppLayout>}
