import React from 'react';
import { BedDouble, Bath, Users, Image } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { StatCard } from '../components/StatCard.jsx';
import { DataTable } from '../components/DataTable.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { formatCurrency, formatPercent } from '../lib/formatters.js';
export function PropertyDetailPage({ propertyId }){ const { data } = useApp(); const property = data.properties.find(p=>p.id===propertyId) || data.properties[0]; if(!property) return <AppLayout title="Property"><section className="card">No property found.</section></AppLayout>; const bookings=data.bookings.filter(b=>b.propertyId===property.id); const cleaning=data.cleaningTasks.filter(t=>t.propertyId===property.id); const maintenance=data.maintenanceWorkOrders.filter(w=>w.propertyId===property.id); return <AppLayout title={property.name}><div className="detail-hero card"><div><h2>{property.name}</h2><p>{property.address}, {property.city}, {property.country}</p><StatusBadge>{property.status}</StatusBadge></div><div className="photo-placeholder"><Image/> Photos placeholder</div></div><div className="stat-grid"><StatCard label="Revenue" value={formatCurrency(property.revenue, property.currency)}/><StatCard label="Expenses" value={formatCurrency(property.expenses, property.currency)}/><StatCard label="Net profit" value={formatCurrency(property.revenue-property.expenses, property.currency)}/><StatCard label="Occupancy" value={formatPercent(property.occupancy)}/></div><section className="card"><h3>Property overview</h3><div className="metadata-grid"><span><BedDouble/> {property.bedrooms} bedrooms</span><span><Bath/> {property.bathrooms} bathrooms</span><span><Users/> {property.maxGuests} max guests</span><span>Owner: {property.owner}</span><span>Cleaner: {property.cleaner}</span><span>Maintenance: {property.maintenanceCrew}</span><span>Rental type: {property.rentalType}</span><span>Rate: {formatCurrency(property.rate, property.currency)}</span></div><p>{property.notes}</p></section><div className="panel-grid"><section className="card"><h3>Bookings</h3><DataTable rows={bookings} columns={[{key:'guest',label:'Guest'},{key:'checkIn',label:'In'},{key:'checkOut',label:'Out'},{key:'status',label:'Status',render:r=><StatusBadge>{r.status}</StatusBadge>}]} /></section><section className="card"><h3>Cleaning history</h3>{cleaning.map(t=><div className="list-row" key={t.id}><span>{t.due}</span><StatusBadge>{t.status}</StatusBadge></div>)}</section><section className="card"><h3>Maintenance history</h3>{maintenance.map(w=><div className="list-row" key={w.id}><span>{w.title}<small>{w.notes}</small></span><StatusBadge>{w.status}</StatusBadge></div>)}</section></div><section className="card"><h3>Owner payout, guest reviews, and notes</h3><p>Owner payout placeholder: {formatCurrency((property.revenue-property.expenses)*0.75, property.currency)}. Guest reviews placeholder and internal notes are ready for production integrations.</p></section></AppLayout>}
