import React from 'react';
import { RefreshCcw, Trash2 } from 'lucide-react';
import { AppLayout } from '../components/layout/AppLayout.jsx';
import { DataTable } from '../components/DataTable.jsx';
import { useApp } from '../lib/AppContext.jsx';
import { currencies, roleLabels } from '../data/constants.js';
import { teamMembers } from '../data/sampleData.js';
import { isSupabaseConfigured } from '../lib/supabase.js';
export function SettingsPage(){ const { currentWorkspace, resetDemoData, resetBlankData }=useApp(); return <AppLayout title="Settings"><div className="settings-grid"><section className="card"><h3>Workspace settings</h3><label>Workspace name<input defaultValue={currentWorkspace.name}/></label><label>Company code<input defaultValue={currentWorkspace.code}/></label><label>Country<input defaultValue={currentWorkspace.country}/></label></section><section className="card"><h3>Currency settings</h3><p>Default currency is stored at workspace level. Live FX conversion is intentionally out of MVP scope.</p><select defaultValue={currentWorkspace.defaultCurrency}>{currencies.map(c=><option key={c}>{c}</option>)}</select></section><section className="card"><h3>Subscription / billing</h3><p>Plan: {currentWorkspace.subscription.plan} · Status: {currentWorkspace.subscription.status} · Billing: {currentWorkspace.subscription.billingPeriod}</p><p>Property limit: {currentWorkspace.subscription.propertyLimit} · User limit: {currentWorkspace.subscription.userLimit} · Trial: {String(currentWorkspace.subscription.trial)}</p><button>Manage billing</button><small className="todo">TODO: Connect Stripe customer portal.</small></section><section className="card"><h3>Notifications</h3><label><input type="checkbox" defaultChecked/> Owner report ready</label><label><input type="checkbox" defaultChecked/> Cleaning overdue</label><label><input type="checkbox" defaultChecked/> Urgent maintenance issue</label></section><section className="card full"><h3>Team members, roles, and permissions</h3><DataTable rows={teamMembers} columns={[{key:'name',label:'Name'},{key:'roles',label:'Roles',render:r=>r.roles.map(role=>roleLabels[role]).join(', ')},{key:'status',label:'Status'}]} /></section><section className="card full danger-zone"><h3>Demo data reset tools</h3>{!isSupabaseConfigured && <p className="helper">Supabase not configured: buttons update local sample state only. Production write logic can call Supabase RPCs later.</p>}<button onClick={resetDemoData}><RefreshCcw size={16}/> Reset to sample data</button><button className="danger" onClick={resetBlankData}><Trash2 size={16}/> Reset all data to blank</button></section></div></AppLayout>}
