-- Optional local-development seed placeholder for PropFlow Phase 1.
-- Production/customer accounts should be created through Supabase Auth and the app workspace setup flow.
-- Do not run demo customer data in production.
