import React from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ChartCard } from '../ChartCard.jsx';
import { bookingSources, financialSeries, priorityBreakdown, profitBreakdown } from '../../data/sampleData.js';
const colors = ['#1B998B', '#2563EB', '#16A34A', '#D97706', '#DC2626'];
export function RevenueCharts() {
  return <div className="chart-grid"><ChartCard title="Revenue vs expenses" subtitle="Net profitability trend"><ResponsiveContainer width="100%" height={260}><AreaChart data={financialSeries}><CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area dataKey="revenue" stroke="#1B998B" fill="#1B998B22" /><Area dataKey="expenses" stroke="#D97706" fill="#D9770622" /><Line dataKey="profit" stroke="#2563EB" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Profit breakdown" subtitle="Owner payout and operating margin"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={profitBreakdown} dataKey="value" outerRadius={90} label>{profitBreakdown.map((_, i) => <Cell key={i} fill={colors[i % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard></div>;
}
export function OperationsCharts() {
  return <div className="chart-grid"><ChartCard title="Occupancy trend" subtitle="Across active properties"><ResponsiveContainer width="100%" height={220}><LineChart data={financialSeries}><CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line dataKey="occupancy" stroke="#1B998B" strokeWidth={2} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Booking source breakdown" subtitle="Direct booking snapshot included"><ResponsiveContainer width="100%" height={220}><BarChart data={bookingSources}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#2563EB" /></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Maintenance cost trend" subtitle="Estimated vs actual ready"><ResponsiveContainer width="100%" height={220}><LineChart data={financialSeries}><XAxis dataKey="month" /><YAxis /><Tooltip /><Line dataKey="maintenance" stroke="#DC2626" /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Cleaning completion rate" subtitle="Guest-ready velocity"><ResponsiveContainer width="100%" height={220}><AreaChart data={financialSeries}><XAxis dataKey="month" /><YAxis /><Tooltip /><Area dataKey="cleaning" stroke="#16A34A" fill="#16A34A22" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Work order priority breakdown" subtitle="Urgent issues surfaced"><ResponsiveContainer width="100%" height={220}><BarChart data={priorityBreakdown}><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#D97706" /></BarChart></ResponsiveContainer></ChartCard></div>;
}
